version: "3.9"
services:
#  app:
#    build: .
#    container_name: "auth-service-rust"
#    restart: always
#    volumes:
#      - .:/app
#    command: sh -c "cargo watch -x run"

  db:
    image: postgres:13
    restart: always
    container_name: "auth-service-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_service
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    restart: always
    container_name: "auth-service-redis"
    ports:
      - "6379:6379"
  redis-test:
    image: redis:latest
    restart: always
    container_name: "auth-service-redis-test"
    ports:
      - "6380:6379"
